# Generated by Django 5.2.12 on 2026-05-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamingsession',
            new_name='gaming_gami_game_co_28e52a_idx',
            old_name='gaming_sess_game_co_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='gamingsession',
            new_name='gaming_gami_game_co_09fa56_idx',
            old_name='gaming_sess_game_co_kind_ts_idx',
        ),
        migrations.AddField(
            model_name='gamingsession',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
