# Generated by Django 5.2.12 on 2026-03-14 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivativeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('strategy_name', models.CharField(max_length=120)),
                ('market', models.CharField(choices=[('cme', 'CME'), ('b3', 'B3'), ('otc', 'OTC')], max_length=20)),
                ('purpose', models.CharField(choices=[('hedge', 'Hedge'), ('speculation', 'Speculation'), ('protection', 'Protection')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivative_operations', to='clients.broker')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivative_operations', to='clients.clientaccount')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivative_operations', to='clients.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivative_operations', to='catalog.crop')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivative_operations', to='clients.economicgroup')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivative_operations', to='clients.cropseason')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivative_operations', to='clients.subgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DerivativeLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('leg_type', models.CharField(choices=[('future', 'Future'), ('call', 'Call'), ('put', 'Put'), ('swap', 'Swap')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('contract_size', models.DecimalField(decimal_places=4, max_digits=18)),
                ('strike', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('premium_currency', models.CharField(blank=True, max_length=10)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('settlement_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('is_otc', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs', to='catalog.marketinstrument')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='derivatives.derivativeoperation')),
            ],
        ),
        migrations.CreateModel(
            name='CashSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=10)),
                ('settlement_type', models.CharField(choices=[('premium', 'Premium'), ('variation', 'Variation'), ('final', 'Final')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
                ('derivative_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_settlements', to='derivatives.derivativeoperation')),
            ],
            options={
                'ordering': ['-settlement_date'],
            },
        ),
        migrations.CreateModel(
            name='MarkToMarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('gross_mtm', models.DecimalField(decimal_places=2, max_digits=18)),
                ('premium_effect', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_mtm', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=10)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('derivative_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtm_snapshots', to='derivatives.derivativeoperation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AddIndex(
            model_name='derivativeoperation',
            index=models.Index(fields=['tenant', 'client', 'trade_date'], name='derivatives_tenant__3cba32_idx'),
        ),
        migrations.AddIndex(
            model_name='derivativeoperation',
            index=models.Index(fields=['tenant', 'status'], name='derivatives_tenant__80979e_idx'),
        ),
        migrations.AddIndex(
            model_name='derivativeleg',
            index=models.Index(fields=['operation', 'instrument'], name='derivatives_operati_3e0369_idx'),
        ),
        migrations.AddIndex(
            model_name='marktomarketsnapshot',
            index=models.Index(fields=['tenant', 'snapshot_date'], name='derivatives_tenant__063391_idx'),
        ),
    ]
