# Generated by Django 5.2.12 on 2026-03-15 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_cropyear_remove_priceunit_currency_and_more'),
        ('clients', '0002_remove_counterparty_uq_counterparty_name_tenant_and_more'),
        ('derivatives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsettlement',
            name='derivative_operation',
        ),
        migrations.RemoveField(
            model_name='cashsettlement',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='derivativeleg',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='derivativeleg',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='marktomarketsnapshot',
            name='derivative_operation',
        ),
        migrations.RemoveField(
            model_name='marktomarketsnapshot',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='derivativeoperation',
            options={'ordering': ['-data_contratacao', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='derivativeoperation',
            name='derivatives_tenant__3cba32_idx',
        ),
        migrations.RemoveIndex(
            model_name='derivativeoperation',
            name='derivatives_tenant__80979e_idx',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='counterparty',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='market',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='season',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='settlement_date',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='strategy_name',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='derivativeoperation',
            name='trade_date',
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='cod_operacao_mae',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='compra_venda',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='contraparte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivativos', to='clients.counterparty'),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='contrato_derivativo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivativos', to='catalog.crop'),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='custo_total_montagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='data_liquidacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivativos', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='liquidacao_ajuste_total_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='liquidacao_ajuste_total_moeda_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='liquidacao_dolar_ptax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='moeda_ou_cmdtye',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='moeda_unidade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='nome_da_operacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivativos', to='clients.cropseason'),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivativos', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='tipo_derivativo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='unidade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='volume_financeiro_moeda',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='volume_financeiro_valor_moeda_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='volume_financeiro_valor_moeda_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='volume_fisico',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='volume_fisico_unidade_padrao_cultura',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.DeleteModel(
            name='CashSettlement',
        ),
        migrations.DeleteModel(
            name='DerivativeLeg',
        ),
        migrations.DeleteModel(
            name='MarkToMarketSnapshot',
        ),
    ]
