# Generated by Django 5.2.12 on 2026-03-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0007_remove_derivativeoperation_liquidacao_ajuste_total_moeda_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='derivativeoperation',
            options={'ordering': ['cod_operacao_mae', 'ordem', 'id']},
        ),
        migrations.RenameField(
            model_name='derivativeoperation',
            old_name='volume_fisico',
            new_name='volume',
        ),
    ]
