# Generated by Django 5.2.12 on 2026-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0009_derivativeoperation_destino_cultura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derivativeoperation',
            old_name='grupo_montagem',
            new_name='posicao',
        ),
        migrations.AddField(
            model_name='derivativeoperation',
            name='obs',
            field=models.TextField(blank=True, verbose_name='Obs'),
        ),
    ]
