# Generated by Django 5.2.12 on 2026-03-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0010_remove_derivativeoperation_grupo_montagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derivativeoperation',
            old_name='unidade',
            new_name='volume_fisico_unidade',
        ),
        migrations.RenameField(
            model_name='derivativeoperation',
            old_name='volume',
            new_name='volume_fisico_valor',
        ),
        migrations.RenameField(
            model_name='derivativeoperation',
            old_name='volume_financeiro_valor_moeda_original',
            new_name='volume_financeiro_valor',
        ),
        migrations.AlterField(
            model_name='derivativeoperation',
            name='posicao',
            field=models.CharField(blank=True, max_length=20, verbose_name='Posicao'),
        ),
        migrations.AlterField(
            model_name='derivativeoperation',
            name='volume_financeiro_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Volume financeiro valor'),
        ),
        migrations.AlterField(
            model_name='derivativeoperation',
            name='volume_fisico_unidade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Volume fisico unidade'),
        ),
        migrations.AlterField(
            model_name='derivativeoperation',
            name='volume_fisico_valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Volume fisico valor'),
        ),
    ]
