# Generated by Django 5.2.12 on 2026-03-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_derivativeoperationname'),
        ('derivatives', '0011_remove_derivativeoperation_unidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derivativeoperation',
            old_name='cultura',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='derivativeoperation',
            old_name='moeda_unidade',
            new_name='strike_moeda_unidade',
        ),
        migrations.AlterField(
            model_name='derivativeoperation',
            name='ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivativos', to='catalog.crop', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='derivativeoperation',
            name='strike_moeda_unidade',
            field=models.CharField(blank=True, max_length=30, verbose_name='Strike moeda unidade'),
        ),
    ]
