# Generated by Django 5.2.12 on 2026-03-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derivatives', '0012_remove_derivativeoperation_cultura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivativeoperation',
            name='swap_divida',
            field=models.CharField(blank=True, max_length=10, verbose_name='Se for Moeda Swap de Divida'),
        ),
    ]
