# Generated by Django 5.2.12 on 2026-03-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0005_rename_clients_sub_tenant__a95ab3_idx_clients_sub_tenant__147ca3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_subgroups',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='clients.subgroup'),
        ),
    ]
