# Generated by Django 5.2.12 on 2026-03-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_groups_user_assigned_subgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo')], default='active', max_length=20),
        ),
    ]
