# Generated by Django 5.2.12 on 2026-03-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_limits_for_groups_subgroups_invitations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='accounts_in_tenant__991c2e_idx',
            old_name='accounts_in_tenant__c87443_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='accounts_in_tenant__f8253b_idx',
            old_name='accounts_in_tenant__1112d8_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='accounts_in_token_be8e6c_idx',
            old_name='accounts_in_token_637d78_idx',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='max_groups',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='max_invitations',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='max_subgroups',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='subscription_status',
        ),
    ]
