# Generated by Django 5.2.12 on 2026-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_invitation_accepted_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='max_groups',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='max_invitations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='max_subgroups',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
