# Generated by Django 5.2.12 on 2026-03-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_invitation_max_groups_invitation_max_invitations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
