# Generated by Django 5.2.12 on 2026-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_invitation_kind_and_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='requires_master_user',
            field=models.BooleanField(default=False),
        ),
    ]
