# Generated by Django 5.2.12 on 2026-03-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_tenant_requires_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='can_register_groups',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='can_register_subgroups',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='can_send_invitations',
            field=models.BooleanField(default=True),
        ),
    ]
