# Generated by Django 5.2.12 on 2026-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_tenant_can_register_groups_and_more'),
        ('clients', '0006_economicgroup_owner_economicgroup_users_with_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='max_groups',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='max_invitations',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='max_subgroups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_invitations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_subgroups',
        ),
        migrations.AddField(
            model_name='invitation',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='invitations', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='assigned_subgroups',
            field=models.ManyToManyField(blank=True, related_name='invitations', to='clients.subgroup'),
        ),
    ]
