# Generated by Django 5.2.12 on 2026-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_invitation_max_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_admin_invitations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_owned_groups',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_owned_subgroups',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
