# Generated by Django 5.2.12 on 2026-03-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_max_admin_invitations_user_max_owned_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Cadastro realizado'), ('expired', 'Expirado')], default='pending', max_length=20),
        ),
    ]
