# Generated by Django 5.2.12 on 2026-04-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_recreate_assigned_subgroups_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='assigned_groups',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='assigned_subgroups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_subgroups',
        ),
    ]
