# Generated by Django 5.2.12 on 2026-05-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_cep_user_cidade_user_cpf_user_endereco_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_test',
            field=models.BooleanField(default=False, help_text="Convite de usuario teste: a conta cai no tenant 'teste', sem carteira."),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Tenant de testes: dados isolados, fora de qualquer carteira/relatorio/ranking.'),
        ),
    ]
