# Generated by Django 5.2.12 on 2026-03-14 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='clients.clientaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='catalog.crop')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='clients.cropseason')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trigger_type', models.CharField(choices=[('price', 'Price'), ('fx', 'FX'), ('basis', 'Basis'), ('volume', 'Volume')], max_length=20)),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '=')], max_length=10)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('target_text', models.CharField(blank=True, max_length=120)),
                ('action_type', models.CharField(choices=[('alert', 'Alert'), ('execute', 'Execute'), ('review', 'Review')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('reference_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('fired', 'Fired'), ('ignored', 'Ignored'), ('executed', 'Executed')], max_length=20)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='strategies.strategytrigger')),
            ],
        ),
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(fields=('tenant', 'client', 'season', 'name'), name='uq_strategy_name'),
        ),
    ]
