# Generated by Django 5.2.12 on 2026-03-15 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0004_delete_unitofmeasure'),
        ('clients', '0002_remove_counterparty_uq_counterparty_name_tenant_and_more'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('bolsa_ref', models.CharField(blank=True, max_length=50)),
                ('monitorar_vc', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True)),
                ('produtividade', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('producao_total', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('criar_politica_hedge', models.BooleanField(default=False)),
                ('unidade_producao', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HedgePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumos_travados_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('insumos_travados_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('margem_alvo_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('mes_ano', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True)),
                ('vendas_x_custo_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('vendas_x_custo_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('vendas_x_prod_total_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('vendas_x_prod_total_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'ordering': ['-mes_ano', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='triggerevent',
            name='trigger',
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['-data_validade', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='strategytrigger',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='strategy',
            name='uq_strategy_name',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='client',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='season',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='name',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='target_text',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='strategytrigger',
            name='trigger_type',
        ),
        migrations.AddField(
            model_name='strategy',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='descricao_estrategia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='strategy',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='acima_abaixo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='codigo_derivativo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='codigos_estrategia',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='contrato_bolsa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatilhos', to='catalog.crop'),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='estrategia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatilhos', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='gatilhos', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='posicao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='produto_bolsa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='status_gatilho',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='strike_alvo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='subgrupos',
            field=models.ManyToManyField(blank=True, related_name='gatilhos', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='tipo_fis_der',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='unidade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='cropboard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropboard',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadros_safra', to='catalog.crop'),
        ),
        migrations.AddField(
            model_name='cropboard',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='quadros_safra', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='cropboard',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadros_safra', to='clients.cropseason'),
        ),
        migrations.AddField(
            model_name='cropboard',
            name='subgrupos',
            field=models.ManyToManyField(blank=True, related_name='quadros_safra', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='cropboard',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='hedgepolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hedgepolicy',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicas_hedge', to='catalog.crop'),
        ),
        migrations.AddField(
            model_name='hedgepolicy',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='politicas_hedge', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='hedgepolicy',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicas_hedge', to='clients.cropseason'),
        ),
        migrations.AddField(
            model_name='hedgepolicy',
            name='subgrupos',
            field=models.ManyToManyField(blank=True, related_name='politicas_hedge', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='hedgepolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
        migrations.DeleteModel(
            name='TriggerEvent',
        ),
    ]
