# Generated by Django 5.2.12 on 2026-04-05 03:28

import django.db.models.deletion
from django.db import migrations, models


def backfill_strategy_trigger_fields(apps, schema_editor):
    StrategyTrigger = apps.get_model("strategies", "StrategyTrigger")

    for trigger in StrategyTrigger.objects.select_related("estrategia").all():
        dirty_fields = []

        if not trigger.tenant_id and getattr(trigger, "estrategia_id", None):
            trigger.tenant_id = trigger.estrategia.tenant_id
            dirty_fields.append("tenant")

        if not trigger.tipo and trigger.tipo_fis_der:
            trigger.tipo = trigger.tipo_fis_der
            dirty_fields.append("tipo")

        if not trigger.bolsa and trigger.produto_bolsa:
            trigger.bolsa = trigger.produto_bolsa
            dirty_fields.append("bolsa")

        if not trigger.contrato_derivativo and trigger.contrato_bolsa:
            trigger.contrato_derivativo = trigger.contrato_bolsa
            dirty_fields.append("contrato_derivativo")

        if trigger.strike is None and trigger.strike_alvo is not None:
            trigger.strike = trigger.strike_alvo
            dirty_fields.append("strike")

        if trigger.volume_objetivo is None and trigger.volume is not None:
            trigger.volume_objetivo = trigger.volume
            dirty_fields.append("volume_objetivo")

        if dirty_fields:
            trigger.save(update_fields=dirty_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_cep_user_cidade_user_cpf_user_endereco_completo_and_more'),
        ('strategies', '0005_remove_cropboard_grupos_remove_cropboard_subgrupos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategytrigger',
            name='bolsa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='contrato_derivativo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='strike',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_triggers', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='volume_objetivo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.RunPython(backfill_strategy_trigger_fields, migrations.RunPython.noop),
    ]
