# Generated by Django 5.2.12 on 2026-05-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_cropboard_data_colheita_cropboard_data_plantio'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategytrigger',
            name='alert_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='alert_state',
            field=models.CharField(default='armed', max_length=20),
        ),
        migrations.AddField(
            model_name='strategytrigger',
            name='alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TriggerAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(blank=True, max_length=120)),
                ('direction', models.CharField(blank=True, max_length=20)),
                ('strike', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('email_sent', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='strategies.strategytrigger')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['trigger', '-sent_at'], name='strategies__trigger_1c7fde_idx')],
            },
        ),
    ]
