# Generated by Django 5.2.12 on 2026-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0009_strategytrigger_alert_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropboard',
            name='margem_alvo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margem alvo em % (ex.: 15.50 = 15,50%)', max_digits=7, null=True),
        ),
    ]
