# Generated by Django 5.2.12 on 2026-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedgePositionLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(blank=True, max_length=150)),
                ('cultura', models.CharField(blank=True, max_length=80)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('mensagem', models.TextField(blank=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('origem', models.CharField(blank=True, max_length=150)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Hedge Position',
                'verbose_name_plural': 'Leads Hedge Position',
                'db_table': 'lead_hedgeposition',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
