# Generated by Django 5.2.12 on 2026-05-17 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0033_create_teste_tenant'),
        ('catalog', '0016_alter_exchange_tv_symbol_fmt_and_more'),
        ('clients', '0011_remove_counterparty_clients_cou_tenant__06be5d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfinementDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('consumo_ms_kg_dia', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Consumo de MS (kg/cabeca/dia)')),
                ('custo_ms_brl_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Custo da MS (R$/kg)')),
                ('pct_milho', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='% do custo da dieta exposto ao milho (0-100)')),
                ('milho_kg_cabeca_dia', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Milho (kg/cabeca/dia) -- p/ dimensionar hedge CCM')),
                ('obs', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfinementLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_lote', models.CharField(blank=True, max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=160)),
                ('bolsa_ref', models.CharField(blank=True, max_length=60, verbose_name='Bolsa ref. (ex.: B3/BGI)')),
                ('cabecas', models.PositiveIntegerField(blank=True, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('peso_entrada_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso medio de entrada (kg/cabeca)')),
                ('gmd_kg_dia', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='GMD projetado (kg/dia)')),
                ('dias_cocho', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_saida_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso medio de saida (kg/cabeca) -- derivado, override permitido')),
                ('peso_saida_manual', models.BooleanField(default=False, verbose_name='Peso de saida informado manualmente')),
                ('rendimento_carcaca', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rendimento de carcaca (%) -- peso vivo -> @')),
                ('data_saida_projetada', models.DateField(blank=True, null=True, verbose_name='Data de saida projetada -- derivada (entrada + dias)')),
                ('reposicao_status', models.CharField(blank=True, choices=[('travada', 'Travada (custo fixo)'), ('em_aberto', 'Em aberto (referencia + risco de base)')], default='em_aberto', max_length=20)),
                ('preco_reposicao', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Preco reposicao (fixo se travada / referencia se em aberto)')),
                ('reposicao_unidade', models.CharField(blank=True, choices=[('rs_arroba', 'R$/@'), ('rs_cabeca', 'R$/cabeca'), ('rs_kg', 'R$/kg vivo')], default='rs_cabeca', max_length=12)),
                ('regiao_base', models.CharField(blank=True, max_length=80, verbose_name='Regiao p/ base local vs ESALQ (reposicao em aberto)')),
                ('preco_boi_gordo_ref', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Preco boi gordo a vista ref. (R$/@) -- override CEPEA')),
                ('status', models.CharField(blank=True, choices=[('planejado', 'Planejado'), ('em_cocho', 'Em cocho'), ('encerrado', 'Encerrado')], default='planejado', max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_confinamento', to='catalog.crop', verbose_name='Ativo (ex.: Boi Gordo)')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_confinamento', to='clients.clientaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('dieta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='cattle.confinementdiet')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_confinamento', to='clients.economicgroup')),
                ('safra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_confinamento', to='clients.cropseason')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_confinamento', to='clients.subgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at', 'codigo_lote'],
            },
        ),
        migrations.AddIndex(
            model_name='confinementdiet',
            index=models.Index(fields=['tenant', 'nome'], name='cattle_conf_tenant__a170a2_idx'),
        ),
        migrations.AddIndex(
            model_name='confinementlot',
            index=models.Index(fields=['tenant', 'status'], name='cattle_conf_tenant__fc2f52_idx'),
        ),
        migrations.AddIndex(
            model_name='confinementlot',
            index=models.Index(fields=['tenant', 'subgrupo', 'safra'], name='cattle_conf_tenant__6de474_idx'),
        ),
    ]
