# Generated by Django 5.2.12 on 2026-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confinementlot',
            name='arrobas_hedge',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='@ travadas via BGI/B3'),
        ),
        migrations.AddField(
            model_name='confinementlot',
            name='arrobas_por_cabeca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='@ previstas por cabeca (saida)'),
        ),
        migrations.AddField(
            model_name='confinementlot',
            name='cabecas_vendidas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cabecas ja vendidas (fisico, boi gordo)'),
        ),
        migrations.AddField(
            model_name='confinementlot',
            name='preco_hedge_arroba',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Preco medio do hedge BGI (R$/@)'),
        ),
        migrations.AddField(
            model_name='confinementlot',
            name='preco_venda_arroba',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Preco medio de venda (R$/@)'),
        ),
    ]
