# Generated by Django 5.2.12 on 2026-05-09 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0031_user_cep_user_cidade_user_cpf_user_endereco_completo_and_more'),
        ('clients', '0011_remove_counterparty_clients_cou_tenant__06be5d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta', models.CharField(blank=True, max_length=120)),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('moeda', models.CharField(blank=True, default='R$', max_length=20)),
                ('considerar_no_fluxo', models.BooleanField(default=True)),
                ('obs', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balances', to='clients.economicgroup')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balances', to='clients.subgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Caixa disponivel e aplicacao',
                'verbose_name_plural': 'Caixa disponivel e aplicacoes',
                'ordering': ['banco', 'conta', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'banco'], name='cash_balanc_tenant__06e17c_idx'), models.Index(fields=['tenant', 'considerar_no_fluxo'], name='cash_balanc_tenant__47ece1_idx')],
            },
        ),
    ]
