# Generated by Django 5.2.12 on 2026-04-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0031_user_cep_user_cidade_user_cpf_user_endereco_completo_and_more'),
        ('clients', '0011_remove_counterparty_clients_cou_tenant__06be5d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.CharField(choices=[('current', 'Cenário Atual'), ('sim_1', 'Simulação 1'), ('sim_2', 'Simulação 2'), ('proj_2027', 'Projeção 2027'), ('proj_2028', 'Projeção 2028')], default='current', max_length=20)),
                ('table', models.CharField(choices=[('balanco', 'Balanço'), ('dre', 'DRE')], max_length=20)),
                ('key', models.CharField(max_length=150)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='clients.economicgroup')),
                ('safra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='clients.cropseason')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['table', 'scenario', 'key'],
                'unique_together': {('tenant', 'grupo', 'safra', 'scenario', 'table', 'key')},
            },
        ),
    ]
