# Generated by Django 5.2.12 on 2026-03-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingViewWatchlistQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField()),
                ('watchlist_id', models.CharField(max_length=50)),
                ('watchlist_name', models.CharField(blank=True, max_length=120)),
                ('section_name', models.CharField(blank=True, max_length=120)),
                ('symbol', models.CharField(max_length=80)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('ticker', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('change_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('instrument_type', models.CharField(blank=True, max_length=40)),
                ('instrument_subtype', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField()),
                ('synced_at', models.DateTimeField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'symbol'],
                'constraints': [models.UniqueConstraint(fields=('source_url', 'symbol'), name='uq_tradingview_watchlist_quote_source_symbol')],
            },
        ),
    ]
