# Generated by Django 5.2.12 on 2026-03-14 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('derivatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField()),
                ('delivery_start', models.DateField()),
                ('delivery_end', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(default='BRL', max_length=10)),
                ('basis', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('gross_value_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('gross_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_sales', to='clients.clientaccount')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_sales', to='clients.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_sales', to='catalog.crop')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_sales', to='clients.economicgroup')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_sales', to='clients.cropseason')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_sales', to='clients.subgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_sales', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HedgeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('allocation_type', models.CharField(choices=[('direct', 'Direct'), ('partial', 'Partial'), ('strategic', 'Strategic')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hedge_allocations', to='catalog.unitofmeasure')),
                ('derivative_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='derivatives.derivativeoperation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
                ('physical_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='physical.physicalsale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='physicalsale',
            index=models.Index(fields=['tenant', 'client', 'trade_date'], name='physical_ph_tenant__584b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalsale',
            index=models.Index(fields=['tenant', 'status'], name='physical_ph_tenant__b5d956_idx'),
        ),
        migrations.AddIndex(
            model_name='hedgeallocation',
            index=models.Index(fields=['tenant', 'physical_sale'], name='physical_he_tenant__d45ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='hedgeallocation',
            index=models.Index(fields=['tenant', 'derivative_operation'], name='physical_he_tenant__0f54da_idx'),
        ),
    ]
