# Generated by Django 5.2.12 on 2026-03-15 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0003_delete_cropyear_remove_priceunit_currency_and_more'),
        ('clients', '0002_remove_counterparty_uq_counterparty_name_tenant_and_more'),
        ('physical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo_despesa', models.CharField(max_length=120)),
                ('moeda', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['grupo_despesa', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('considerar_na_politica_de_hedge', models.BooleanField(default=False)),
                ('grupo_despesa', models.CharField(max_length=120)),
                ('moeda', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['grupo_despesa', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cotacao', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cultura_texto', models.CharField(max_length=100)),
                ('data_pgto', models.DateField(blank=True, null=True)),
                ('data_report', models.DateField(blank=True, null=True)),
                ('localidade', models.CharField(blank=True, max_length=120)),
                ('moeda_unidade', models.CharField(max_length=30)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-data_report', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='hedgeallocation',
            name='allocated_unit',
        ),
        migrations.RemoveField(
            model_name='hedgeallocation',
            name='derivative_operation',
        ),
        migrations.RemoveField(
            model_name='hedgeallocation',
            name='physical_sale',
        ),
        migrations.RemoveField(
            model_name='hedgeallocation',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='physicalsale',
            options={'ordering': ['-data_negociacao', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='physicalsale',
            name='physical_ph_tenant__584b7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='physicalsale',
            name='physical_ph_tenant__b5d956_idx',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='basis',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='client',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='counterparty',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='delivery_end',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='delivery_start',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='gross_value_brl',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='gross_value_usd',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='group',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='season',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='status',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='trade_date',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='unit',
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='basis_moeda',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='basis_valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='bolsa_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='cif_fob',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='compra_venda',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='contraparte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_fisico', to='clients.counterparty'),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='contrato_bolsa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='cotacao_bolsa_ref',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_fisico', to='catalog.crop'),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='cultura_produto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='data_negociacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='dolar_de_venda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='faturamento_total_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='vendas_fisico', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='moeda_contrato',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='objetivo_venda_dolarizada',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='pf_paf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_fisico', to='clients.cropseason'),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='subgrupos',
            field=models.ManyToManyField(blank=True, related_name='vendas_fisico', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='unidade_contrato',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='physicalsale',
            name='volume_fisico',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_realizados', to='catalog.crop'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_realizados', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_realizados', to='clients.cropseason'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_realizados', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='actualcost',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='budgetcost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetcost',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_orcamento', to='catalog.crop'),
        ),
        migrations.AddField(
            model_name='budgetcost',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_orcamento', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='budgetcost',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_orcamento', to='clients.cropseason'),
        ),
        migrations.AddField(
            model_name='budgetcost',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_orcamento', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='budgetcost',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='physicalquote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalquote',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_fisico', to='clients.cropseason'),
        ),
        migrations.AddField(
            model_name='physicalquote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
        migrations.DeleteModel(
            name='HedgeAllocation',
        ),
    ]
