# Generated by Django 5.2.12 on 2026-03-15 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0012_derivativeoperationname'),
        ('clients', '0004_remove_subgroup_grupo_and_more'),
        ('physical', '0004_remove_physicalsale_contrato_bolsa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('moeda', models.CharField(blank=True, max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('contraparte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtos_caixa', to='clients.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtos_caixa', to='clients.economicgroup')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtos_caixa', to='clients.subgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-data_pagamento', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('contraparte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtos_fisico', to='clients.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('fazer_frente_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtos_fisico', to='catalog.crop')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtos_fisico', to='clients.economicgroup')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtos_fisico', to='clients.subgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-data_pagamento', '-created_at'],
            },
        ),
    ]
