# Generated by Django 5.2.12 on 2026-03-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_subgroup_grupo_and_more'),
        ('physical', '0005_cashpayment_physicalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalpayment',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgtos_fisico', to='clients.cropseason'),
        ),
    ]
