# Generated by Django 5.2.12 on 2026-03-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0008_cashpayment_volume_total_operacao_and_more'),
        ('physical', '0009_physicalsale_localidade_contrato_bolsa_obs'),
    ]

    operations = [
    ]
