# Generated by Django 5.2.12 on 2026-03-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0010_merge_20260325_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='data_desembolso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
