# Generated by Django 5.2.12 on 2026-03-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0011_cashpayment_data_desembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='volume_total_operacao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valor total da operacao'),
        ),
    ]
