# Generated by Django 5.2.12 on 2026-03-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0012_alter_cashpayment_volume_total_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalpayment',
            name='classificacao',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='physicalpayment',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
