# Generated by Django 5.2.12 on 2026-03-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0013_physicalpayment_classificacao_physicalpayment_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpayment',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
