# Generated by Django 5.2.12 on 2026-03-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0014_cashpayment_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualcost',
            name='data_travamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
