# Generated by Django 5.2.12 on 2026-04-05 23:03

from django.db import migrations, models


def backfill_cash_payment_fields(apps, schema_editor):
    CashPayment = apps.get_model("physical", "CashPayment")
    Counterparty = apps.get_model("clients", "Counterparty")

    counterparty_map = {
        item.id: (item.contraparte or item.obs or "").strip()
        for item in Counterparty.objects.all().only("id", "contraparte", "obs")
    }

    for row in CashPayment.objects.all().iterator():
        updates = {}
        if row.valor is None and row.volume is not None:
            updates["valor"] = row.volume
        if not row.contraparte_texto and row.contraparte_id:
            updates["contraparte_texto"] = counterparty_map.get(row.contraparte_id, "")
        if updates:
            CashPayment.objects.filter(pk=row.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0015_actualcost_data_travamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashpayment',
            options={'ordering': ['data_pagamento', 'data_vencimento', '-created_at'], 'verbose_name': 'Pgto caixa', 'verbose_name_plural': 'Pgtos caixa'},
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='contraparte_texto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor'),
        ),
        migrations.RunPython(backfill_cash_payment_fields, migrations.RunPython.noop),
    ]
