# Generated by Django 5.2.12 on 2026-05-15 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_cep_user_cidade_user_cpf_user_endereco_completo_and_more'),
        ('catalog', '0016_alter_exchange_tv_symbol_fmt_and_more'),
        ('clients', '0011_remove_counterparty_clients_cou_tenant__06be5d_idx'),
        ('physical', '0017_rename_cashpayment_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moeda', models.CharField(blank=True, max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor_orcado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('data_realizado', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('cultura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos', to='catalog.crop')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos', to='clients.economicgroup')),
                ('safra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos', to='clients.cropseason')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos', to='clients.subgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Custo',
                'verbose_name_plural': 'Custos',
                'ordering': ['-data_realizado', '-created_at'],
            },
        ),
    ]
