# Generated by Django 5.2.12 on 2026-05-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0018_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalsale',
            name='basis_moeda',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='basis_valor',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='bolsa_ref',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='cotacao_bolsa_ref',
        ),
        migrations.RemoveField(
            model_name='physicalsale',
            name='dolar_de_venda',
        ),
    ]
