# Generated by Django 5.2.12 on 2026-05-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0019_remove_physicalsale_basis_moeda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custo',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
