# Generated by Django 5.2.12 on 2026-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0020_custo_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalquote',
            name='preco_brl',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='physicalquote',
            name='preco_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
