# Generated by Django 5.2.12 on 2026-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0022_backfill_physicalquote_precos'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalquote',
            name='basis',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='physicalquote',
            name='bolsa_basis',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
