# Generated by Django 5.2.12 on 2026-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0024_consolidate_physicalquote_currency_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalquote',
            name='moeda_unidade_basis',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
