# Generated by Django 5.2.12 on 2026-05-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0025_physicalquote_moeda_unidade_basis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalquote',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='physicalquote',
            name='moeda_unidade',
        ),
    ]
