# Generated by Django 5.2.12 on 2026-05-17 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_create_teste_tenant'),
        ('clients', '0011_remove_counterparty_clients_cou_tenant__06be5d_idx'),
        ('physical', '0026_remove_physicalquote_cotacao_moeda_unidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preco_brl', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('preco_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('basis', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('bolsa_basis', models.CharField(blank=True, max_length=120)),
                ('moeda_unidade_basis', models.CharField(blank=True, max_length=30)),
                ('cultura_texto', models.CharField(max_length=100)),
                ('data_pgto', models.DateField(blank=True, null=True)),
                ('data_report', models.DateField(blank=True, null=True)),
                ('localidade', models.CharField(blank=True, max_length=120)),
                ('obs', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('safra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes', to='clients.cropseason')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'db_table': 'cotacoes',
                'ordering': ['-data_report', '-created_at'],
            },
        ),
    ]
