# Generated by Django 5.2.12 on 2026-05-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0027_cotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalsale',
            name='pf_paf',
        ),
    ]
