# Generated by Django 5.2.12 on 2026-04-05 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_cep_user_cidade_user_cpf_user_endereco_completo_and_more'),
        ('other_entries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otherentry',
            new_name='other_entri_tenant__23836b_idx',
            old_name='other_entri_tenant__2bcaa6_idx',
        ),
        migrations.RenameIndex(
            model_name='otherentry',
            new_name='other_entri_tenant__56e423_idx',
            old_name='other_entri_tenant__7df5c6_idx',
        ),
        migrations.RenameIndex(
            model_name='otherentry',
            new_name='other_entri_tenant__72db6c_idx',
            old_name='other_entri_tenant__f08758_idx',
        ),
        migrations.RenameIndex(
            model_name='otherentry',
            new_name='other_entri_tenant__d13fc3_idx',
            old_name='other_entri_tenant__6ec0f9_idx',
        ),
        migrations.AlterField(
            model_name='otherentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otherentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant'),
        ),
    ]
