# Generated by Django 5.2.12 on 2026-04-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_entries', '0002_rename_other_entri_tenant__2bcaa6_idx_other_entri_tenant__23836b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherentry',
            options={'ordering': ['-data_entrada', '-created_at'], 'verbose_name': 'Outra entrada Caixa', 'verbose_name_plural': 'Outras entradas Caixa'},
        ),
    ]
