# Generated by Django 5.2.12 on 2026-04-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_entries', '0003_alter_otherentry_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otherentry',
            name='other_entri_tenant__56e423_idx',
        ),
        migrations.RemoveField(
            model_name='otherentry',
            name='data_vencimento',
        ),
    ]
