# Generated by Django 5.2.12 on 2026-03-14 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('document', models.CharField(blank=True, max_length=30)),
                ('profile_type', models.CharField(choices=[('producer', 'Producer'), ('cooperative', 'Cooperative'), ('trader', 'Trader'), ('industry', 'Industry')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('counterparty_type', models.CharField(choices=[('buyer', 'Buyer'), ('broker', 'Broker'), ('bank', 'Bank'), ('exchange', 'Exchange')], max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='clients.clientaccount')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='catalog.crop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='clients.clientaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='clients.economicgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uq_broker_name_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['tenant', 'name'], name='clients_cli_tenant__5b729e_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'document'), name='uq_client_document_tenant'),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_counterparty_name_tenant'),
        ),
        migrations.AddIndex(
            model_name='cropseason',
            index=models.Index(fields=['tenant', 'client', 'crop'], name='clients_cro_tenant__ba41a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cropseason',
            constraint=models.UniqueConstraint(fields=('tenant', 'client', 'crop', 'season_label'), name='uq_crop_season'),
        ),
        migrations.AddIndex(
            model_name='economicgroup',
            index=models.Index(fields=['tenant', 'client'], name='clients_eco_tenant__33a5b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='economicgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'client', 'code'), name='uq_group_code_client'),
        ),
        migrations.AddIndex(
            model_name='subgroup',
            index=models.Index(fields=['tenant', 'group'], name='clients_sub_tenant__e6332b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'group', 'code'), name='uq_subgroup_code_group'),
        ),
    ]
