# Generated by Django 5.2.12 on 2026-03-15 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='counterparty',
            name='uq_counterparty_name_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='cropseason',
            name='uq_crop_season',
        ),
        migrations.RemoveConstraint(
            model_name='economicgroup',
            name='uq_group_code_client',
        ),
        migrations.RemoveConstraint(
            model_name='subgroup',
            name='uq_subgroup_code_group',
        ),
        migrations.RemoveIndex(
            model_name='cropseason',
            name='clients_cro_tenant__ba41a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='economicgroup',
            name='clients_eco_tenant__33a5b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='subgroup',
            name='clients_sub_tenant__e6332b_idx',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='counterparty_type',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cropseason',
            name='client',
        ),
        migrations.RemoveField(
            model_name='cropseason',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='cropseason',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cropseason',
            name='season_label',
        ),
        migrations.RemoveField(
            model_name='cropseason',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='economicgroup',
            name='client',
        ),
        migrations.RemoveField(
            model_name='economicgroup',
            name='code',
        ),
        migrations.RemoveField(
            model_name='economicgroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrapartes', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrapartes', to='clients.subgroup'),
        ),
        migrations.AddField(
            model_name='cropseason',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safras', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='cropseason',
            name='safra',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='economicgroup',
            name='grupo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrupos', to='clients.economicgroup'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='subgrupo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['tenant', 'grupo'], name='clients_cou_tenant__c4ad42_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['tenant', 'subgrupo'], name='clients_cou_tenant__06be5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cropseason',
            index=models.Index(fields=['tenant', 'safra'], name='clients_cro_tenant__66da0d_idx'),
        ),
        migrations.AddIndex(
            model_name='economicgroup',
            index=models.Index(fields=['tenant', 'grupo'], name='clients_eco_tenant__f349d8_idx'),
        ),
        migrations.AddIndex(
            model_name='subgroup',
            index=models.Index(fields=['tenant', 'grupo'], name='clients_sub_tenant__5a1a7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cropseason',
            constraint=models.UniqueConstraint(fields=('tenant', 'safra', 'grupo'), name='uq_safra_tenant_grupo'),
        ),
        migrations.AddConstraint(
            model_name='economicgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'grupo'), name='uq_group_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='subgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'grupo', 'subgrupo'), name='uq_subgroup_name_group'),
        ),
    ]
