# Generated by Django 5.2.12 on 2026-03-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0002_remove_counterparty_uq_counterparty_name_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cropseason',
            name='uq_safra_tenant_grupo',
        ),
        migrations.RemoveField(
            model_name='cropseason',
            name='grupo',
        ),
        migrations.AddConstraint(
            model_name='cropseason',
            constraint=models.UniqueConstraint(fields=('tenant', 'safra'), name='uq_safra_tenant'),
        ),
    ]
