# Generated by Django 5.2.12 on 2026-03-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_subgroup_grupo_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subgroup',
            new_name='clients_sub_tenant__147ca3_idx',
            old_name='clients_sub_tenant__a95ab3_idx',
        ),
    ]
