# Generated by Django 5.2.12 on 2026-03-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_economicgroup_owner_economicgroup_users_with_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='contraparte',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
