# Generated by Django 5.2.12 on 2026-04-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_restore_subgroup_group_hierarchy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='counterparty',
            name='clients_cou_tenant__06be5d_idx',
        ),
    ]
