# Generated by Django 5.2.12 on 2026-03-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cropyear_currency_investmenttype_alter_crop_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropYear',
        ),
        migrations.RemoveField(
            model_name='priceunit',
            name='currency',
        ),
        migrations.DeleteModel(
            name='InvestmentType',
        ),
        migrations.RemoveField(
            model_name='priceunit',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['cultura']},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='code',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='marketinstrument',
            name='asset_class',
        ),
        migrations.RemoveField(
            model_name='marketinstrument',
            name='quote_currency',
        ),
        migrations.AddField(
            model_name='crop',
            name='cultura',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='quote_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='contract_size',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='PriceUnit',
        ),
    ]
