# Generated by Django 5.2.12 on 2026-03-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_cropyear_remove_priceunit_currency_and_more'),
        ('physical', '0002_actualcost_budgetcost_physicalquote_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitOfMeasure',
        ),
    ]
