# Generated by Django 5.2.12 on 2026-04-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_rename_cultura_to_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['ativo']},
        ),
    ]
