# Generated by Django 5.2.12 on 2026-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_exchange_tv_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='tv_symbol_fmt',
            field=models.CharField(blank=True, help_text='Formato do símbolo TradingView (ano 4 dígitos). Ex: BMFBOVESPA:DOL{month}{year4} ou CBOT:ZS{month}{year4}', max_length=80),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='tv_ticker_fmt',
            field=models.CharField(blank=True, help_text='Formato do ticker no DB (ano 2 dígitos). Ex: DOL{month}{year} ou ZS{month}{year}', max_length=60),
        ),
    ]
