# Generated by Django 5.2.12 on 2026-03-14 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposurePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('expected_production', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('physical_sold', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('hedge_volume', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('open_exposure', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('avg_physical_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('avg_hedge_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('mtm_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('mtm_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('hedge_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposure_positions', to='clients.clientaccount')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposure_positions', to='catalog.crop')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposure_positions', to='clients.economicgroup')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposure_positions', to='clients.cropseason')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposure_positions', to='clients.subgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-reference_date'],
                'indexes': [models.Index(fields=['tenant', 'reference_date'], name='risk_exposu_tenant__79b50d_idx'), models.Index(fields=['tenant', 'client', 'season'], name='risk_exposu_tenant__128a96_idx')],
            },
        ),
    ]
