# Generated by Django 5.2.12 on 2026-04-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0031_user_cep_user_cidade_user_cpf_user_endereco_completo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret', models.CharField(max_length=500)),
                ('calendar_id', models.CharField(default='primary', help_text='ID da agenda do Google. Use "primary" para a agenda principal.', max_length=300)),
                ('refresh_token', models.TextField(blank=True)),
                ('conectada', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Configuracao Google Calendar',
                'verbose_name_plural': 'Configuracoes Google Calendar',
                'ordering': ['nome'],
                'unique_together': {('tenant', 'nome')},
            },
        ),
    ]
