# Generated by Django 5.2.12 on 2026-04-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_delete_agendaeventmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientagendaevent',
            name='participantes',
            field=models.TextField(blank=True),
        ),
    ]
