# Generated by Django 5.2.12 on 2026-03-14 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'ordering': ['-rate_date'],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'rate_date'), name='uq_fx_rate')],
            },
        ),
        migrations.CreateModel(
            name='BasisSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=120)),
                ('basis_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basis_series', to='catalog.crop')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basis_series', to='catalog.pricesource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-basis_date'],
                'indexes': [models.Index(fields=['tenant', 'crop', 'basis_date'], name='marketdata__tenant__7d9604_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField()),
                ('price_time', models.TimeField(blank=True, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('settlement_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='catalog.marketinstrument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_prices', to='catalog.pricesource')),
            ],
            options={
                'ordering': ['-price_date'],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'source', 'price_date', 'price_time'), name='uq_market_price_ref')],
            },
        ),
    ]
