# Generated by Django 5.2.12 on 2026-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=80)),
                ('quote_date', models.DateField()),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', '-quote_date'],
                'indexes': [models.Index(fields=['symbol', 'quote_date'], name='marketdata__symbol_bb24c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'quote_date'), name='uq_historicalquote_symbol_date')],
            },
        ),
    ]
