# Generated by Django 5.2.12 on 2026-05-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_historicalquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConabBasisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('week_count', models.PositiveIntegerField(default=0)),
                ('last_week', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
