# Generated by Django 5.2.12 on 2026-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_conabbasissnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SojaCrushSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('latest_market_year', models.PositiveIntegerField(default=0)),
                ('source_note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
