# Generated by Django 5.2.12 on 2026-04-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0031_user_cep_user_cidade_user_cpf_user_endereco_completo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingFieldIgnoredConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=120)),
                ('resource_label', models.CharField(blank=True, max_length=160)),
                ('field_name', models.CharField(max_length=120)),
                ('field_label', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_field_ignored_configs', to='accounts.tenant')),
            ],
            options={
                'ordering': ['resource_label', 'field_label', 'id'],
                'indexes': [models.Index(fields=['tenant', 'resource'], name='insights_mi_tenant__87c1b3_idx'), models.Index(fields=['tenant', 'field_name'], name='insights_mi_tenant__ae037d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'resource', 'field_name'), name='uq_missing_field_ignored_config_scope')],
            },
        ),
    ]
