# Generated by Django 5.2.12 on 2026-03-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0002_auditlog_alteracoes_auditlog_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='stored_content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='attachment',
            name='stored_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
