# Generated by Django 5.2.12 on 2026-04-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0003_attachment_file_blob_attachment_stored_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='alteracoes',
        ),
    ]
