# Generated by Django 5.2.12 on 2026-03-24 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_alter_invitation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=220)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('categorias', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status_artigo', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=20)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('texto_completo', models.TextField(blank=True)),
                ('html_embed', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('imagem_capa', models.FileField(blank=True, null=True, upload_to='market_news/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='market_news/audio/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_market_news_posts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Market news post',
                'verbose_name_plural': 'Market news posts',
                'ordering': ['-data_publicacao', '-created_at'],
            },
        ),
    ]
