# Generated by Django 5.2.12 on 2026-04-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_marketnewspost_index_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketnewspost',
            options={'ordering': ['-data_publicacao', '-created_at'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
        migrations.RemoveIndex(
            model_name='marketnewspost',
            name='mercado_mnp_ordering_idx',
        ),
    ]
